Repository xkbcommon/libxkbcommon, pull requests merged in 2024-09, with the labels that each got.

#502 Add XKB_LED_NAME_COMPOSE and XKB_LED_NAME_KANA
  changes/api/+compose-and-kana-led-names.features.md
  include/xkbcommon/xkbcommon-names.h
Labels: enhancement, state

#499 rules: Fix wild card handling
  changes/api/497.bugfix.md
  doc/rules-format.md
  src/xkbcomp/rules.c
  test/data/rules/groups
  test/data/rules/wildcard
  test/rules-file.c
Labels: bug, X11 legacy: compatibility

#517 Fix typo in darray_enumerate_from
  src/darray.h
Labels: bug
