Repository xkbcommon/libxkbcommon, pull requests merged in 2025-04, with the labels that each got.

#702 keymap: Use constants for Lock and Control indexes
  src/keymap-priv.c
  src/keymap.h
  src/state.c
Labels: state

#701 xkbcomp: Drop trailing NoSymbol and NoAction()
  changes/api/+drop-trailing-empty-actions-and-keysyms.breaking.md
  doc/keymap-format-text-v1.md
  src/xkbcomp/symbols.c
  test/buffercomp.c
  test/data/keymaps/merge-modes/augment.xkb
  test/data/keymaps/merge-modes/default.xkb
  test/data/keymaps/merge-modes/override.xkb
  test/data/keymaps/merge-modes/replace.xkb
  test/data/keymaps/symbols-multi-keysyms-empty.xkb
Labels: compile-keymap

#706 tools: Update bash completion
  tools/xkbcli-bash-completion.sh
Labels: tools: compile-keymap, tools: compile-compose

#708 Support multiple actions in interpret
  changes/api/695.feature.md
  doc/keymap-format-text-v1.md
  src/keymap.c
  src/keymap.h
  src/x11/keymap.c
  src/xkbcomp/compat.c
  src/xkbcomp/keymap-dump.c
  src/xkbcomp/keymap.c
  src/xkbcomp/parser.y
  test/buffercomp.c
  test/data/keymaps/empty-compound-statements.xkb
  test/data/keymaps/stringcomp.data
  test/data/keymaps/symbols-multi-keysyms-empty.xkb
  test/state.c
Labels: compile-keymap

#710 logging: Handle NULL map name
  src/compose/parser.c
  src/xkbcomp/ast-build.h
  src/xkbcomp/compat.c
  src/xkbcomp/keycodes.c
  src/xkbcomp/keymap.c
  src/xkbcomp/parser.y
  src/xkbcomp/symbols.c
  src/xkbcomp/types.c
  src/xkbcomp/xkbcomp-priv.h
Labels: compile-keymap

#711 build: Warn if missing xkbcomp for X11 tests
  meson.build
  test/x11.c
  test/x11comp.c
  test/xvfb-wrapper.c
Labels: build system

#713 Fix integer conversion warnings
  src/utils-numbers.h
  src/xkbcomp/keymap-dump.c
  src/xkbcomp/scanner.c
  test/compose-iter.c
Labels: compiler warning

#718 xkbcomp: Fix Unicode escape sequence
  src/scanner-utils.h
  src/xkbcomp/scanner.c
  test/buffercomp.c
  test/data/keymaps/escape-sequences.xkb
Labels: bug, compile-keymap

#721 test: Improve xkeyboard-config script
  test/xkeyboard-config-test.py.in
Labels: testing

#722 xkbcomp: Safer keycode max_key_code
  src/xkbcomp/keycodes.c
Labels: compile-keymap

#723 test: Enable 3rd party compilers
  meson.build
  scripts/update-merge-modes-tests.py
  test/common.c
  test/external_xkb_compilers.h
  test/merge_modes.c.jinja
  test/test.h
Labels: testing

#731 doc/keymap-format-text-v1: fix inaccurate statement in Keysym glossary entry
  doc/keymap-format-text-v1.md
Labels: documentation

#734 doc: Fix usual vmods mapping typo
  doc/keymap-format-text-v1.md
Labels: documentation

#736 test: Fix `main()` function prototype
  test/keysym-unicode.c
Labels: bug

#733 ExprKeySym: add comment about error recovery
  src/xkbcomp/ast.h
Labels: documentation

#735 doc: Introduce a FAQ page with how to get the vmod → rmod mapping
  README.md
  doc/faq.md
  include/xkbcommon/xkbcommon.h
  meson.build
Labels: documentation, state
