Repository xkbcommon/libxkbcommon, pull requests merged in 2025-02, with the labels that each got.

#614 xkbcomp: rework ActionList and KeysymList AST representation
  src/xkbcomp/ast-build.c
  src/xkbcomp/ast-build.h
  src/xkbcomp/ast.h
  src/xkbcomp/parser.y
  src/xkbcomp/symbols.c
Labels: compile-keymap, performance

#642 xkbcomp/scanner: avoid unneeded strdup of IDENT tokens
  src/scanner-utils.h
  src/xkbcomp/parser-priv.h
  src/xkbcomp/parser.y
  src/xkbcomp/rules.c
  src/xkbcomp/scanner.c
Labels: compile-keymap, performance

#655 scripts: Rename keysyms-related files
  scripts/update-keysyms
  scripts/update-keysyms-case-mappings.py
  scripts/update-keysyms-definitions.py
  scripts/update-keysyms-derived-headers.py
  scripts/update-keysyms-names-handling.py
  src/keysym-case-mappings.c
  src/ks_tables.h
  test/keysym-case-mapping.h
Labels: keysyms generator

#653 tools: Fix compile-keymap default KcCGST values
  tools/compile-keymap.c
Labels: tools: compile-keymap

#661 xkbcomp: Fix incorrect memory comparison
  src/keymap-priv.c
Labels: compiler warning

#664 tools: Do not load names from the environment by default
  changes/tools/+enable-environment-names.breaking.md
  test/tool-option-parsing.py
  tools/compile-keymap.c
  tools/how-to-type.c
  tools/interactive-evdev.c
  tools/xkbcli-compile-keymap.1
  tools/xkbcli-how-to-type.1
  tools/xkbcli-interactive-evdev.1
Labels: bug, tools: interactive, tools: how-to-type, tools: compile-keymap

#665 test: Fix inversion of expected/got in log test
  test/log.c
Labels: testing

#668 doc: Fix link to modules
  README.md
Labels: documentation

#667 doc: Fix cool URIs
  doc/cool-uris.yaml
  scripts/ensure-stable-doc-urls.py
Labels: documentation
